import dedent from 'dedent';
import type { Config, FileHeader, FormatFn } from 'style-dictionary/types';

export const customHeader: FileHeader = (
	defaultMessage?: string[],
	options?: Config,
) => {
	const messages = defaultMessage || [];
	return [`Anwesh Gangula Style Dictionary Design Tokens\n`, ...messages];
};

/**
 * CUSTOM FORMATTER: typescript/const-object
 * Converts W3C ($value) tokens into a nested TypeScript "as const" object.
 */
export const tsTypeSafe: FormatFn = ({
	dictionary,
	platform,
	options,
	file,
}) => {
	// 1. Metadata: The "User Manual" Header
	const header = dedent`
		/**
		 * GENERATED DESIGN TOKENS - DO NOT EDIT
		 * ---------------------------------------
		 * This file was generated by Style Dictionary.
		 * * WHY THIS FORMAT?
		 * - 'as const': Enables Literal Type Inference (Instead of 'string', values are treated as specific hex/pixels).
		 * TypeScript knows the exact value (e.g., '#FFFFFF'). as const Assertion: This is the "magic" that turns a generic string into a literal type (e.g.,#6200EE). This allows Vite to optimize your code and gives you errors if you try to use a color that doesn't exist.
		 * - 'Tokens' Type: Provides full hierarchical autocomplete via dot-notation.
		 * - 'TokenPath' Type: A type-safe union of all possible dot-notation paths.
		 * - 'getTokenByPath()': A runtime utility to safely resolve a path string.
		 * Example: const myColor: TokenPath = "color.brand.primary";.
		 * * HOW TO USE:
		 * import { tokens, type TokenPath } from './build/ts/tokens';
		 * const color = tokens.color.brand.primary; // Type-safe access
		 * interface BoxProps {
				color: TokenPath; // Forces the user to pick a valid token path
				// If someone types "color.red.wrong", TypeScript will flag it!
			}
		*/\n\n`;

	// 2. Recursive function to strip metadata and extract only the resolved values
	const extractValues = (obj: any) => {
		const result: any = {};

		for (const key in obj) {
			if (!obj.hasOwnProperty(key)) continue;

			const token = obj[key];

			// Check if this is a leaf node (a token)
			// SD v4 normalized resolution often puts the final value in .value
			// W3C raw format uses .$value
			const value = token.value ?? token.$value;

			if (value !== undefined) {
				result[key] = value;
			} else if (typeof token === 'object' && token !== null) {
				// If it's a nested group, recurse
				result[key] = extractValues(token);
			}
		}
		return result;
	};

	// 3. Generate the Body
	const reduceOutputSize = false;
	const cleanTokens = reduceOutputSize
		? extractValues(dictionary.tokens)
		: dictionary.tokens;
	const tokensObject = `export const tokens = ${JSON.stringify(cleanTokens, null, 2)} as const;`;

	// 4. CORE TYPES: Necessary for basic TypeScript integration
	const coreTypes = `export type Tokens = typeof tokens;`;

	// 5. UTILITY TYPES: Advanced type-safe path mapping
	const utilityTypes = dedent`/**
		 * Recursive type to generate all possible dot-notation paths from the tokens object.
		*/
		export type TokenPaths<T extends object> = {
		[K in keyof T & string]: T[K] extends object
			? \`\${K}\` | \`\${K}.\${TokenPaths<T[K]>}\`
			: \`\${K}\`;
		}[keyof T & string];

		export type TokenPath = TokenPaths<Tokens>;`;

	// 6. UTILITY FUNCTIONS: Runtime helpers for resolving paths
	const utilityFunctions = dedent`
		/**
		 * Safely retrieves a token value using a type-safe path string.
		 * This bridges the gap between dynamic string inputs and the static tokens object.
		 * @example getTokenByPath('color.brand.primary')
		*/
		export function getTokenByPath(path: TokenPath): any {
		return path.split('.').reduce((prev: any, curr) => prev?.[curr], tokens);
		}`;

	// 7. FINAL ASSEMBLY
	return [header, tokensObject, coreTypes, utilityTypes, utilityFunctions].join(
		'\n\n',
	);
};
