// src/index.ts

// Export the TS tokens generated by Style Dictionary
export * from './sd-build/tokens/ts-type-safe/tokens.ts';
// export * from './src/sd-build/tokens/ts/tokens.js';

// If you want to help users find the CSS path (optional helper)
export const tokenPaths = {
	css: './tokens/css/variables.css',
	scss: './tokens/scss/_variables.scss',
};
