# Printout
# prints inputs

defaults:
  run:
    shell: bash

runs:
  using: 'composite'
  steps:
    - name: Print Inputs
      env:
        EVENT_INPUTS: ${{ toJSON(github.event.inputs) }}
      run: |
        echo $EVENT_INPUTS
