name: Post-Merge

on:
  push:
    branches: [main]

jobs:
  quality_control:
    name: Quality-Check
    uses: ./.github/workflows/quality-check.yaml

  # visual_testing:
  #   name: Visual-Testing
  #   uses: ./.github/workflows/visual-testing.yaml

  deploy_docs_dev:
    name: Deploy-Docs-Dev
    # extra control for dev deployment can be achieved
    # needs: [quality_control, visual_testing]
    needs: [quality_control]
    # this can be fine-tuned when issue is resolved
    # https://github.com/actions/runner/issues/2205
    # if: ${{ needs.quality_control.result == 'success' }}
    uses: ./.github/workflows/deploy-docs-dev.yaml

  deploy_apps_dev:
    name: Deploy-Apps-Dev
    # extra control for dev deployment can be achieved
    # needs: [quality_control, visual_testing]
    needs: [quality_control]
    # this can be fine-tuned when issue is resolved
    # https://github.com/actions/runner/issues/2205
    # if: ${{ needs.quality_control.result == 'success' }}
    uses: ./.github/workflows/deploy-apps-dev.yaml
