name: Post-Merge

on:
  push:
    branches: [main]

jobs:
  quality_control:
    name: Quality-Check
    uses: ./.github/workflows/quality-check.yaml

  visual_testing:
    name: Visual-Testing
    uses: ./.github/workflows/visual-testing.yaml

  deploy_docs_dev:
    name: Deploy-Docs-Dev
    needs: [quality_control]
    if: ${{ needs.quality_control.result == 'success' }}
    uses: ./.github/workflows/deploy-docs-dev.yaml

  deploy_apps_dev:
    name: Deploy-Apps-Dev
    needs: [quality_control]
    if: ${{ needs.quality_control.result == 'success' }}
    uses: ./.github/workflows/deploy-apps-dev.yaml
