name: Post-Merge

on:
  push:
    branches: [main]

jobs:
  quality_control:
    name: Quality-Control
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Quality-Check
        uses: ./.github/workflows/quality-check.yaml

      - name: Visual-Testing
        uses: ./.github/workflows/visual-testing.yaml

  deploy_dev:
    name: Deploy-Dev
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: [quality_control]
    if: ${{ needs.quality_control.result == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy-Docs-Dev
        uses: ./.github/workflows/deploy-docs-dev.yaml

      - name: Deploy-Apps-Dev
        uses: ./.github/workflows/deploy-apps-dev.yaml
