name: Quality-Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality_check:
    name: Quality-Check
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint

      - name: Format Check
        run: pnpm format:check

      - name: Build
        run: pnpm build

      - name: Test - UI Library
        run: pnpm --filter "@awsm/ui" test
