name: Visual Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # automatic runs
  workflow_call:
    inputs:
      update-snapshots:
        description: "Update snapshots?"
        type: boolean

  # manual runs
  workflow_dispatch: 
    inputs:
      update-snapshots:
        description: "Update snapshots?"
        type: boolean

jobs:
  build:
    name: Visual Testing
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Playwright
        run: pnpm dlx playwright install --with-deps

      - name: Build
        run: pnpm build

      - name: Set up Cache
        id: cache
        uses: actions/cache@v4
        with:
          key: cache/${{github.repository}}/${{github.ref}}
          restore-keys: cache/${{github.repository}}/refs/heads/main
          path: apps/storybook/.test/**

      - name: Initialize snapshots
        if: ${{steps.cache.outputs.cache-hit != 'true' || inputs.update-snapshots == 'true'}}
        run: pnpm --filter "awsm-storybook" test:update --reporter html

      - name: Test - Visual Regressions
        run: pnpm --filter "awsm-storybook" test

      - name: Upload Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/storybook/.test/report/
          retention-days: 10
          overwrite: true
